package server_test

import (
	"context"
	"database/sql"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/MauricioPerera/librarian/internal/auth"
)

// server_articles_test.go implements CONTRACT-03 T4: end-to-end authorization
// tests over the articles CRUD surface. It reuses the helpers in
// server_auth_test.go (openAuthMux, doJSON, roleID, testSecret, timeNowUTC) —
// same package — and adds a few small grant/identity helpers below.
//
// Role/permission setup note: SeedCatalogs (CONTRACT-02) seeds only the role
// and permission *names*; role_permissions (which role has which permission)
// is not seeded. Each test grants the specific permissions it needs to the
// roles it uses, so the grant state is explicit and per-test.
//
//   - "editor"   → granted all four content.* permissions; the "with perm"
//                 identity and the fixture creator.
//   - "author"   → granted NO permissions; the authenticated-but-without-perm
//                 identity (403 on gated routes, 200 on reads).
//   - API keys   → minted against "editor" (has perms) to exercise the
//                 service-identity path, including the design-decision reject
//                 on POST.

// permissionID looks up a permission id by name.
func permissionID(t *testing.T, db *sql.DB, name string) string {
	t.Helper()
	var id string
	if err := db.QueryRow(`SELECT id FROM permissions WHERE name = ?`, name).Scan(&id); err != nil {
		t.Fatalf("lookup permission %q: %v", name, err)
	}
	return id
}

// grant inserts role_permissions rows for the given role/permissions
// idempotently. It is the test-only equivalent of an admin assigning a
// permission to a role.
func grant(t *testing.T, db *sql.DB, role string, perms ...string) {
	t.Helper()
	rid := roleID(t, db, role)
	for _, p := range perms {
		pid := permissionID(t, db, p)
		if _, err := db.Exec(
			`INSERT INTO role_permissions (role_id, permission_id) VALUES (?, ?) ON CONFLICT DO NOTHING`,
			rid, pid,
		); err != nil {
			t.Fatalf("grant %q to %q: %v", p, role, err)
		}
	}
}

// jwtFor creates a user with the given role and returns a fresh JWT for it.
func jwtFor(t *testing.T, db *sql.DB, email, password, role string) string {
	t.Helper()
	ctx := context.Background()
	if _, err := auth.CreateUser(ctx, db, email, password, []string{role}); err != nil {
		t.Fatalf("create user %q: %v", email, err)
	}
	user, err := auth.VerifyCredentials(ctx, db, email, password)
	if err != nil {
		t.Fatalf("verify %q: %v", email, err)
	}
	token, err := auth.IssueJWT(testSecret, user, timeNowUTC())
	if err != nil {
		t.Fatalf("issue jwt: %v", err)
	}
	return token
}

// apiKeyFor mints an API key bound to the given role and returns the plaintext
// secret.
func apiKeyFor(t *testing.T, db *sql.DB, label, role string) string {
	t.Helper()
	rid := roleID(t, db, role)
	secret, err := auth.MintAPIKey(context.Background(), db, label, rid)
	if err != nil {
		t.Fatalf("mint api key: %v", err)
	}
	return secret
}

// authHeader wraps a bearer token into an Authorization header map.
func authHeader(token string) map[string]string {
	return map[string]string{"Authorization": "Bearer " + token}
}

// createArticle POSTs an article as the given token and returns the new id.
func createArticle(t *testing.T, srv *httptest.Server, token, title, body string) string {
	t.Helper()
	status, resp := doJSON(t, srv, http.MethodPost, "/articles",
		map[string]string{"title": title, "body": body}, authHeader(token))
	if status != http.StatusCreated {
		t.Fatalf("create article: status=%d body=%v, want 201", status, resp)
	}
	id, _ := resp["id"].(string)
	if id == "" {
		t.Fatalf("create article: no id in response %v", resp)
	}
	return id
}

// nonexistentID is a valid-format UUID that is never generated by
// gen_random_uuid(), so it is guaranteed absent — used to exercise the 404
// path on every gated route.
const nonexistentID = "11111111-1111-1111-1111-111111111111"

// --- T1: content.update seeded ---------------------------------------------

// TestContentUpdatePermissionSeeded confirms T1: after SeedCatalogs (called
// inside openAuthMux), SELECT finds the content.update row.
func TestContentUpdatePermissionSeeded(t *testing.T) {
	db, _, cleanup := openAuthMux(t)
	defer cleanup()
	var id string
	err := db.QueryRow(`SELECT id FROM permissions WHERE name = 'content.update'`).Scan(&id)
	if err != nil {
		t.Fatalf("content.update not seeded: %v", err)
	}
	if id == "" {
		t.Fatal("content.update seeded with empty id")
	}
}

// --- T3/T4: POST /articles (content.create) -------------------------------

// TestCreateArticle covers the create acceptance criterion: with the perm →
// 201 + a real row; without the perm → 403; unauthenticated → 401.
func TestCreateArticle(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create", "content.update", "content.publish", "content.delete")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	authorToken := jwtFor(t, db, "au@example.com", "pw", "author") // no grants

	// With perm → 201 + real row.
	status, body := doJSON(t, srv, http.MethodPost, "/articles",
		map[string]string{"title": "Hello", "body": "World"}, authHeader(editorToken))
	if status != http.StatusCreated {
		t.Fatalf("with-perm status=%d body=%v, want 201", status, body)
	}
	id, _ := body["id"].(string)
	if id == "" {
		t.Fatalf("no id returned: %v", body)
	}
	var title string
	if err := db.QueryRow(`SELECT title FROM articles WHERE id = ?`, id).Scan(&title); err != nil {
		t.Fatalf("row not in DB: %v", err)
	}
	if title != "Hello" {
		t.Fatalf("title in DB = %q, want Hello", title)
	}

	// Without perm → 403.
	status, _ = doJSON(t, srv, http.MethodPost, "/articles",
		map[string]string{"title": "x", "body": "y"}, authHeader(authorToken))
	if status != http.StatusForbidden {
		t.Fatalf("without-perm status=%d, want 403", status)
	}

	// Unauthenticated → 401.
	status, _ = doJSON(t, srv, http.MethodPost, "/articles",
		map[string]string{"title": "x", "body": "y"}, nil)
	if status != http.StatusUnauthorized {
		t.Fatalf("unauth status=%d, want 401", status)
	}
}

// TestCreateArticleWithMetadata covers CONTRACT-04 T2's extension to POST
// /articles: an optional metadata JSON value is stored verbatim in the
// articles.metadata column. Omitting it keeps the original NULL default, so the
// CONTRACT-03 surface is backward compatible. This runs in the default suite
// (green twice); the end-to-end export fixture is the tagged test below.
func TestCreateArticleWithMetadata(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")

	// With a real JSON metadata value → 201 + stored verbatim.
	status, body := doJSON(t, srv, http.MethodPost, "/articles",
		map[string]any{"title": "With Meta", "body": "B", "metadata": map[string]any{"tags": []string{"a", "b"}, "n": 1}},
		authHeader(editorToken))
	if status != http.StatusCreated {
		t.Fatalf("with-metadata status=%d body=%v, want 201", status, body)
	}
	id, _ := body["id"].(string)
	if id == "" {
		t.Fatalf("no id returned: %v", body)
	}
	var meta sql.NullString
	if err := db.QueryRow(`SELECT metadata FROM articles WHERE id = ?`, id).Scan(&meta); err != nil {
		t.Fatalf("select metadata: %v", err)
	}
	if !meta.Valid || meta.String == "" {
		t.Fatalf("metadata not stored: %+v", meta)
	}
	// The stored text must be valid JSON carrying the sent fields.
	var got map[string]any
	if err := json.Unmarshal([]byte(meta.String), &got); err != nil {
		t.Fatalf("stored metadata not valid JSON: %q: %v", meta.String, err)
	}
	if _, ok := got["tags"]; !ok {
		t.Fatalf("stored metadata lost tags: %v", got)
	}

	// Omitting metadata → NULL (backward compatible with CONTRACT-03).
	status, body = doJSON(t, srv, http.MethodPost, "/articles",
		map[string]any{"title": "No Meta", "body": "B"}, authHeader(editorToken))
	if status != http.StatusCreated {
		t.Fatalf("no-metadata status=%d body=%v, want 201", status, body)
	}
	id2, _ := body["id"].(string)
	var meta2 sql.NullString
	if err := db.QueryRow(`SELECT metadata FROM articles WHERE id = ?`, id2).Scan(&meta2); err != nil {
		t.Fatalf("select metadata2: %v", err)
	}
	if meta2.Valid && meta2.String != "" {
		t.Fatalf("omitted metadata should be NULL, got %q", meta2.String)
	}
}

// one whose role has content.create) cannot create an article because it has
// no human author — articles.author_id is NOT NULL → reject with 403 + a
// clear message.
func TestCreateArticleAPIKeyRejected(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create")
	key := apiKeyFor(t, db, "svc", "editor")

	status, body := doJSON(t, srv, http.MethodPost, "/articles",
		map[string]string{"title": "x", "body": "y"}, authHeader(key))
	if status != http.StatusForbidden {
		t.Fatalf("apikey-create status=%d, want 403", status)
	}
	if msg, _ := body["error"].(string); msg == "" {
		t.Fatalf("expected clear error message, got %v", body)
	}
}

// --- T3/T4: GET /articles and GET /articles/{id} --------------------------

// TestListAndGetArticles covers the read acceptance criterion: any
// authenticated identity (JWT with no perms, AND an API key) → 200;
// unauthenticated → 401.
func TestListAndGetArticles(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	authorToken := jwtFor(t, db, "au@example.com", "pw", "author") // no perms
	key := apiKeyFor(t, db, "svc", "editor")

	id := createArticle(t, srv, editorToken, "T1", "B1")

	// JWT (no perms) → 200 on list.
	if status, _ := doJSON(t, srv, http.MethodGet, "/articles", nil, authHeader(authorToken)); status != http.StatusOK {
		t.Fatalf("list jwt-noperm status=%d, want 200", status)
	}
	// API key → 200 on list.
	if status, _ := doJSON(t, srv, http.MethodGet, "/articles", nil, authHeader(key)); status != http.StatusOK {
		t.Fatalf("list apikey status=%d, want 200", status)
	}
	// JWT → 200 on get one.
	if status, _ := doJSON(t, srv, http.MethodGet, "/articles/"+id, nil, authHeader(authorToken)); status != http.StatusOK {
		t.Fatalf("get jwt status=%d, want 200", status)
	}
	// Unauthenticated list → 401.
	if status, _ := doJSON(t, srv, http.MethodGet, "/articles", nil, nil); status != http.StatusUnauthorized {
		t.Fatalf("list unauth status=%d, want 401", status)
	}
	// Unauthenticated get one → 401.
	if status, _ := doJSON(t, srv, http.MethodGet, "/articles/"+id, nil, nil); status != http.StatusUnauthorized {
		t.Fatalf("get unauth status=%d, want 401", status)
	}
}

// --- T3/T4: PUT /articles/{id} (content.update) ----------------------------

// TestUpdateArticle covers the update criterion: with content.update → 200 +
// changes persisted; without → 403.
func TestUpdateArticle(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create", "content.update")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	authorToken := jwtFor(t, db, "au@example.com", "pw", "author") // no update

	id := createArticle(t, srv, editorToken, "Old", "OldBody")

	// With perm → 200 + persisted.
	status, body := doJSON(t, srv, http.MethodPut, "/articles/"+id,
		map[string]string{"title": "New", "body": "NewBody"}, authHeader(editorToken))
	if status != http.StatusOK {
		t.Fatalf("with-perm status=%d body=%v, want 200", status, body)
	}
	var title, artBody string
	if err := db.QueryRow(`SELECT title, body FROM articles WHERE id = ?`, id).Scan(&title, &artBody); err != nil {
		t.Fatalf("select: %v", err)
	}
	if title != "New" || artBody != "NewBody" {
		t.Fatalf("persisted = (%q,%q), want (New,NewBody)", title, artBody)
	}

	// Without perm → 403, and the row is unchanged.
	status, _ = doJSON(t, srv, http.MethodPut, "/articles/"+id,
		map[string]string{"title": "Hack", "body": "Hack"}, authHeader(authorToken))
	if status != http.StatusForbidden {
		t.Fatalf("without-perm status=%d, want 403", status)
	}
	if err := db.QueryRow(`SELECT title FROM articles WHERE id = ?`, id).Scan(&title); err != nil {
		t.Fatalf("select: %v", err)
	}
	if title != "New" {
		t.Fatalf("row changed after 403: title=%q, want New", title)
	}
}

// --- T3/T4: POST /articles/{id}/publish (content.publish) ------------------

// TestPublishArticle covers publish + idempotency: with content.publish → 200
// + published_at set; calling twice does not fail and published_at does not
// change. Without the perm → 403.
func TestPublishArticle(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create", "content.publish")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	authorToken := jwtFor(t, db, "au@example.com", "pw", "author") // no publish

	id := createArticle(t, srv, editorToken, "Draft", "Body")

	// Without perm → 403 (published_at still NULL).
	if status, _ := doJSON(t, srv, http.MethodPost, "/articles/"+id+"/publish", nil, authHeader(authorToken)); status != http.StatusForbidden {
		t.Fatalf("without-perm status=%d, want 403", status)
	}

	// First publish → 200, published_at set.
	status, body := doJSON(t, srv, http.MethodPost, "/articles/"+id+"/publish", nil, authHeader(editorToken))
	if status != http.StatusOK {
		t.Fatalf("first publish status=%d body=%v, want 200", status, body)
	}
	first, _ := body["published_at"].(string)
	if first == "" {
		t.Fatalf("first publish published_at empty: %v", body)
	}
	// Confirm NULL→set in the DB.
	var dbPub sql.NullString
	if err := db.QueryRow(`SELECT published_at FROM articles WHERE id = ?`, id).Scan(&dbPub); err != nil {
		t.Fatalf("select: %v", err)
	}
	if !dbPub.Valid || dbPub.String == "" {
		t.Fatalf("published_at not set in DB: %+v", dbPub)
	}

	// Second publish → 200 (no failure), published_at UNCHANGED.
	status, body = doJSON(t, srv, http.MethodPost, "/articles/"+id+"/publish", nil, authHeader(editorToken))
	if status != http.StatusOK {
		t.Fatalf("second publish status=%d, want 200 (idempotent)", status)
	}
	second, _ := body["published_at"].(string)
	if second != first {
		t.Fatalf("idempotency broken: first=%q second=%q", first, second)
	}
}

// --- T3/T4: DELETE /articles/{id} (content.delete) -------------------------

// TestDeleteArticle covers the delete criterion: with content.delete → 204
// + row gone; without → 403.
func TestDeleteArticle(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.create", "content.delete")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	authorToken := jwtFor(t, db, "au@example.com", "pw", "author") // no delete

	id := createArticle(t, srv, editorToken, "Bye", "Body")

	// Without perm → 403, row still present.
	if status, _ := doJSON(t, srv, http.MethodDelete, "/articles/"+id, nil, authHeader(authorToken)); status != http.StatusForbidden {
		t.Fatalf("without-perm status=%d, want 403", status)
	}
	if !exists(t, db, id) {
		t.Fatal("row disappeared after 403")
	}

	// With perm → 204 + row gone.
	status, _ := doJSON(t, srv, http.MethodDelete, "/articles/"+id, nil, authHeader(editorToken))
	if status != http.StatusNoContent && status != http.StatusOK {
		t.Fatalf("with-perm status=%d, want 204/200", status)
	}
	if exists(t, db, id) {
		t.Fatal("row still present after delete")
	}
}

// exists reports whether an article row with the given id is present.
func exists(t *testing.T, db *sql.DB, id string) bool {
	t.Helper()
	var x int
	err := db.QueryRow(`SELECT 1 FROM articles WHERE id = ?`, id).Scan(&x)
	if err == sql.ErrNoRows {
		return false
	}
	if err != nil {
		t.Fatalf("exists check: %v", err)
	}
	return true
}

// --- Red-team: 404 paths (missing + malformed id) -------------------------

// TestNotFound confirms every gated route returns 404 — never 500/panic — for
// a valid-format id that does not exist.
func TestNotFound(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.update", "content.publish", "content.delete")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	h := authHeader(editorToken)

	cases := []struct {
		method, path string
	}{
		{http.MethodGet, "/articles/" + nonexistentID},
		{http.MethodPut, "/articles/" + nonexistentID},
		{http.MethodPost, "/articles/" + nonexistentID + "/publish"},
		{http.MethodDelete, "/articles/" + nonexistentID},
	}
	for _, c := range cases {
		status, body := doJSON(t, srv, c.method, c.path,
			map[string]string{"title": "x", "body": "y"}, h)
		if status != http.StatusNotFound {
			t.Fatalf("%s %s status=%d body=%v, want 404", c.method, c.path, status, body)
		}
	}
}

// TestMalformedIDIsNotFound is the explicit red-team check: a non-UUID id in
// the URL must NOT yield 500 or a panic — it surfaces as 404 (no row matches).
func TestMalformedIDIsNotFound(t *testing.T) {
	db, srv, cleanup := openAuthMux(t)
	defer cleanup()
	grant(t, db, "editor", "content.update", "content.publish", "content.delete")
	editorToken := jwtFor(t, db, "ed@example.com", "pw", "editor")
	h := authHeader(editorToken)

	cases := []struct {
		method, path string
	}{
		{http.MethodGet, "/articles/not-a-uuid"},
		{http.MethodPut, "/articles/x'OR'1'='1"},
		{http.MethodPost, "/articles/!!!/publish"},
		{http.MethodDelete, "/articles/abc"},
	}
	for _, c := range cases {
		status, body := doJSON(t, srv, c.method, c.path,
			map[string]string{"title": "x", "body": "y"}, h)
		if status != http.StatusNotFound {
			t.Fatalf("%s %s status=%d body=%v, want 404 (not 500)", c.method, c.path, status, body)
		}
	}

	// Sanity: the articles table still exists (an injection-style id did
	// nothing — the query is parameterized).
	var n int
	if err := db.QueryRow(`SELECT COUNT(*) FROM articles`).Scan(&n); err != nil {
		t.Fatalf("articles table missing after malformed-id attempts: %v", err)
	}
}
